-- MySQL Script generated by MySQL Workbench
-- Sun Jul  3 19:58:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema KOD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema KOD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KOD` DEFAULT CHARACTER SET utf8 ;
USE `KOD` ;

-- -----------------------------------------------------
-- Table `KOD`.`access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`access` (
  `id_access` INT(11) NOT NULL AUTO_INCREMENT,
  `access_status` VARCHAR(21) NOT NULL,
  PRIMARY KEY (`id_access`),
  UNIQUE INDEX `access_status` (`access_status` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`addmission_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`addmission_type` (
  `id_addmission_type` INT(11) NOT NULL AUTO_INCREMENT,
  `name_addmission_type` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_addmission_type`),
  UNIQUE INDEX `name_addmission_type_UNIQUE` (`name_addmission_type` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`country` (
  `id_country` INT(11) NOT NULL AUTO_INCREMENT,
  `name_country` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_country`),
  UNIQUE INDEX `name_country_UNIQUE` (`name_country` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`type_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`type_address` (
  `id_type_address` INT(11) NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_type_address`),
  UNIQUE INDEX `type_name_UNIQUE` (`type_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`address` (
  `id_address` INT(11) NOT NULL AUTO_INCREMENT,
  `id_type_addr` INT(11) NOT NULL DEFAULT '1',
  `id_addr_country` INT(11) NOT NULL DEFAULT '1',
  `oblast` VARCHAR(40) NOT NULL,
  `city` VARCHAR(30) NOT NULL,
  `street` VARCHAR(30) NOT NULL,
  `house` SMALLINT(3) NOT NULL,
  `flat` SMALLINT(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id_address`),
  INDEX `fk_id_addr_country_idx` (`id_addr_country` ASC) VISIBLE,
  INDEX `fk_id_type_addr_idx` (`id_type_addr` ASC) VISIBLE,
  CONSTRAINT `fk_id_addr_country`
    FOREIGN KEY (`id_addr_country`)
    REFERENCES `KOD`.`country` (`id_country`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_type_addr`
    FOREIGN KEY (`id_type_addr`)
    REFERENCES `KOD`.`type_address` (`id_type_address`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`attestation_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`attestation_type` (
  `id_attestation_type` INT(11) NOT NULL AUTO_INCREMENT,
  `name_attestation` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_attestation_type`),
  UNIQUE INDEX `name_attestation` (`name_attestation` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`class_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`class_type` (
  `id_class_type` INT(11) NOT NULL AUTO_INCREMENT,
  `name_type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_class_type`),
  UNIQUE INDEX `name_type_UNIQUE` (`name_type` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`degree` (
  `id_degree` INT(11) NOT NULL AUTO_INCREMENT,
  `name_degree` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_degree`),
  UNIQUE INDEX `name_degree` (`name_degree` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`dekanat_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`dekanat_user` (
  `id_dekanat` INT(11) NOT NULL AUTO_INCREMENT,
  `surname_dekanat` VARCHAR(30) NOT NULL,
  `name_dekanat` VARCHAR(30) NOT NULL,
  `patronymic_dekanat` VARCHAR(30) NOT NULL,
  `id_user_dekanat` INT(11) NOT NULL,
  PRIMARY KEY (`id_dekanat`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`depart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`depart` (
  `id_depart` INT(11) NOT NULL AUTO_INCREMENT,
  `name_depart` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`id_depart`),
  UNIQUE INDEX `name_depart` (`name_depart` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`education_stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`education_stage` (
  `id_education_stage` INT(11) NOT NULL AUTO_INCREMENT,
  `name_stage` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`id_education_stage`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`major` (
  `id_major` INT(11) NOT NULL AUTO_INCREMENT,
  `name_major` VARCHAR(100) NOT NULL,
  `m_id_education_stage` INT(11) NOT NULL,
  `code_major` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id_major`),
  UNIQUE INDEX `code_major_UNIQUE` (`code_major` ASC) VISIBLE,
  INDEX `fk_m_id_education_stage_idx` (`m_id_education_stage` ASC) VISIBLE,
  CONSTRAINT `fk_m_id_education_stage`
    FOREIGN KEY (`m_id_education_stage`)
    REFERENCES `KOD`.`education_stage` (`id_education_stage`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`depart_major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`depart_major` (
  `dpm_id_depart` INT(11) NOT NULL,
  `dpm_id_major` INT(11) NOT NULL,
  PRIMARY KEY (`dpm_id_depart`, `dpm_id_major`),
  INDEX `dpm_id_major` (`dpm_id_major` ASC) VISIBLE,
  CONSTRAINT `depart_major_ibfk_1`
    FOREIGN KEY (`dpm_id_depart`)
    REFERENCES `KOD`.`depart` (`id_depart`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `depart_major_ibfk_2`
    FOREIGN KEY (`dpm_id_major`)
    REFERENCES `KOD`.`major` (`id_major`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`subdivision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`subdivision` (
  `id_subdivision` INT(11) NOT NULL AUTO_INCREMENT,
  `name_subdivision` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_subdivision`),
  UNIQUE INDEX `name_subdivision` (`name_subdivision` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`depart_subdivision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`depart_subdivision` (
  `ds_id_subdivision` INT(11) NOT NULL,
  `ds_id_depart` INT(11) NOT NULL,
  PRIMARY KEY (`ds_id_subdivision`, `ds_id_depart`),
  INDEX `ds_id_depart` (`ds_id_depart` ASC) VISIBLE,
  CONSTRAINT `depart_subdivision_ibfk_1`
    FOREIGN KEY (`ds_id_depart`)
    REFERENCES `KOD`.`depart` (`id_depart`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `depart_subdivision_ibfk_2`
    FOREIGN KEY (`ds_id_subdivision`)
    REFERENCES `KOD`.`subdivision` (`id_subdivision`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`discipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`discipline` (
  `id_discipline` INT(11) NOT NULL AUTO_INCREMENT,
  `name_discipline` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_discipline`),
  UNIQUE INDEX `name_discipline` (`name_discipline` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`discipline_class_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`discipline_class_type` (
  `id_dis_class` INT(11) NOT NULL AUTO_INCREMENT,
  `dh_discipline_id` INT(11) NOT NULL,
  `dh_class_type_id` INT(11) NOT NULL,
  `hours` TINYINT(11) NULL DEFAULT '0',
  PRIMARY KEY (`id_dis_class`, `dh_discipline_id`, `dh_class_type_id`),
  INDEX `fk_dh_discipline_id_idx` (`dh_discipline_id` ASC) VISIBLE,
  INDEX `fk_dh_class_type_id_idx` (`dh_class_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_dh_class_type_id`
    FOREIGN KEY (`dh_class_type_id`)
    REFERENCES `KOD`.`class_type` (`id_class_type`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dh_discipline_id`
    FOREIGN KEY (`dh_discipline_id`)
    REFERENCES `KOD`.`discipline` (`id_discipline`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`discipline_major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`discipline_major` (
  `id_dis_maj` INT(11) NOT NULL AUTO_INCREMENT,
  `dm_id_discipline` INT(11) NOT NULL,
  `dm_id_major` INT(11) NOT NULL,
  PRIMARY KEY (`id_dis_maj`, `dm_id_discipline`, `dm_id_major`),
  INDEX `dm_id_major` (`dm_id_major` ASC) VISIBLE,
  INDEX `dm_id_discipline` (`dm_id_discipline` ASC) VISIBLE,
  CONSTRAINT `discipline_major_ibfk_1`
    FOREIGN KEY (`dm_id_major`)
    REFERENCES `KOD`.`major` (`id_major`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `discipline_major_ibfk_2`
    FOREIGN KEY (`dm_id_discipline`)
    REFERENCES `KOD`.`discipline` (`id_discipline`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 198
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`education_basis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`education_basis` (
  `id_education_basis` INT(11) NOT NULL AUTO_INCREMENT,
  `name_education_basis` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`id_education_basis`),
  UNIQUE INDEX `name_education_basis_UNIQUE` (`name_education_basis` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`education_form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`education_form` (
  `id_education_form` INT(11) NOT NULL AUTO_INCREMENT,
  `name_education_form` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_education_form`),
  UNIQUE INDEX `name_education_form_UNIQUE` (`name_education_form` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`flow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`flow` (
  `f_id_group` INT(11) NOT NULL AUTO_INCREMENT,
  `flow_number` SMALLINT(20) NOT NULL,
  PRIMARY KEY (`f_id_group`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`group` (
  `id_group` INT(11) NOT NULL AUTO_INCREMENT,
  `id_education_form` INT(11) NULL DEFAULT NULL,
  `id_major` INT(11) NULL DEFAULT NULL,
  `addmission_year` YEAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id_group`),
  INDEX `id_major_idx` (`id_major` ASC) VISIBLE,
  INDEX `fk_id_education_form_idx` (`id_education_form` ASC) VISIBLE,
  CONSTRAINT `fk_id_education_form`
    FOREIGN KEY (`id_education_form`)
    REFERENCES `KOD`.`education_form` (`id_education_form`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_major`
    FOREIGN KEY (`id_major`)
    REFERENCES `KOD`.`major` (`id_major`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`user` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(15) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `u_id_access` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 66
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`stud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`stud` (
  `id_stud` INT(11) NOT NULL AUTO_INCREMENT,
  `s_id_user` INT(11) NOT NULL,
  `surname_stud` VARCHAR(30) NOT NULL DEFAULT 'Иванов',
  `name_stud` VARCHAR(30) NOT NULL DEFAULT 'Иван',
  `patronymic_stud` VARCHAR(30) NULL DEFAULT NULL,
  `current_mail_stud` VARCHAR(60) NOT NULL,
  `current_phone_stud` VARCHAR(10) NOT NULL,
  `id_education_basis` INT(11) NOT NULL,
  `id_addmission_type` INT(11) NOT NULL,
  `addmission_year` YEAR(4) NOT NULL DEFAULT '0000',
  `gradebook_number` VARCHAR(10) NOT NULL,
  `photo_stud` VARCHAR(50) NULL DEFAULT 'default.png',
  `gender_stud` VARCHAR(2) NOT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_stud`),
  UNIQUE INDEX `current_phone_stud_UNIQUE` (`current_phone_stud` ASC) VISIBLE,
  UNIQUE INDEX `current_mail_stud_UNIQUE` (`current_mail_stud` ASC) VISIBLE,
  UNIQUE INDEX `gradebook_number_UNIQUE` (`gradebook_number` ASC) VISIBLE,
  UNIQUE INDEX `stud_id_user_UNIQUE` (`s_id_user` ASC) VISIBLE,
  INDEX `fkstud_adm_type_idx` (`id_addmission_type` ASC) VISIBLE,
  INDEX `fk_id_education_basis_idx` (`id_education_basis` ASC) VISIBLE,
  CONSTRAINT `fk_id_addmission_type`
    FOREIGN KEY (`id_addmission_type`)
    REFERENCES `KOD`.`addmission_type` (`id_addmission_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_education_basis`
    FOREIGN KEY (`id_education_basis`)
    REFERENCES `KOD`.`education_basis` (`id_education_basis`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_s_id_user`
    FOREIGN KEY (`s_id_user`)
    REFERENCES `KOD`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`group_stud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`group_stud` (
  `gs_group_id` INT(11) NOT NULL,
  `gs_stud_id` INT(11) NOT NULL,
  PRIMARY KEY (`gs_group_id`, `gs_stud_id`),
  INDEX `fk_gs_stud_id_idx` (`gs_stud_id` ASC) VISIBLE,
  CONSTRAINT `fk_gs_group_id`
    FOREIGN KEY (`gs_group_id`)
    REFERENCES `KOD`.`group` (`id_group`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gs_stud_id`
    FOREIGN KEY (`gs_stud_id`)
    REFERENCES `KOD`.`stud` (`id_stud`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`parent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`parent` (
  `id_parent` INT(11) NOT NULL AUTO_INCREMENT,
  `surname_parent` VARCHAR(30) NOT NULL DEFAULT 'Иванов',
  `name_parent` VARCHAR(30) NOT NULL DEFAULT 'Иван',
  `patronymic_parent` VARCHAR(30) NULL DEFAULT NULL,
  `current_phone_parent` VARCHAR(10) NOT NULL,
  `job` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_parent`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`parent_stud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`parent_stud` (
  `id_ps_parent` INT(11) NOT NULL,
  `id_ps_stud` INT(11) NOT NULL,
  PRIMARY KEY (`id_ps_parent`, `id_ps_stud`),
  INDEX `fk_id_ps_stud_idx` (`id_ps_stud` ASC) VISIBLE,
  CONSTRAINT `fk_id_ps_parent`
    FOREIGN KEY (`id_ps_parent`)
    REFERENCES `KOD`.`parent` (`id_parent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_ps_stud`
    FOREIGN KEY (`id_ps_stud`)
    REFERENCES `KOD`.`stud` (`id_stud`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`post` (
  `id_post` INT(11) NOT NULL AUTO_INCREMENT,
  `post_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_post`),
  UNIQUE INDEX `post_name` (`post_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`semester_discipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`semester_discipline` (
  `sd_id_dis_maj` INT(11) NOT NULL,
  `sd_semester` INT(2) NOT NULL,
  `id_attestation_type` INT(11) NOT NULL,
  PRIMARY KEY (`sd_id_dis_maj`, `sd_semester`),
  INDEX `fk_semester_discipline_attestation_type1_idx` (`id_attestation_type` ASC) VISIBLE,
  CONSTRAINT `fk_semester_discipline_attestation_type1`
    FOREIGN KEY (`id_attestation_type`)
    REFERENCES `KOD`.`attestation_type` (`id_attestation_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `semester_discipline_ibfk_2`
    FOREIGN KEY (`sd_id_dis_maj`)
    REFERENCES `KOD`.`discipline_major` (`id_dis_maj`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`stud_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`stud_address` (
  `sa_id_addr` INT(11) NOT NULL,
  `sa_id_stud` INT(11) NOT NULL,
  PRIMARY KEY (`sa_id_addr`, `sa_id_stud`),
  INDEX `fk_sa_id_stud_idx` (`sa_id_stud` ASC) VISIBLE,
  CONSTRAINT `fk_sa_id_addr`
    FOREIGN KEY (`sa_id_addr`)
    REFERENCES `KOD`.`address` (`id_address`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sa_id_stud`
    FOREIGN KEY (`sa_id_stud`)
    REFERENCES `KOD`.`stud` (`id_stud`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`stud_performance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`stud_performance` (
  `sp_id_stud` INT(11) NOT NULL,
  `sp_id_dis_class` INT(11) NOT NULL,
  `date_perform` DATE NOT NULL,
  `points` INT(3) NOT NULL,
  PRIMARY KEY (`sp_id_stud`, `sp_id_dis_class`, `date_perform`),
  INDEX `sp_id_dis_class` (`sp_id_dis_class` ASC) VISIBLE,
  CONSTRAINT `stud_performance_ibfk_1`
    FOREIGN KEY (`sp_id_stud`)
    REFERENCES `KOD`.`stud` (`id_stud`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `stud_performance_ibfk_2`
    FOREIGN KEY (`sp_id_dis_class`)
    REFERENCES `KOD`.`discipline_class_type` (`id_dis_class`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`teach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`teach` (
  `id_teach` INT(11) NOT NULL AUTO_INCREMENT,
  `surname_teach` VARCHAR(30) NOT NULL,
  `name_teach` VARCHAR(30) NOT NULL,
  `patronymic_teach` VARCHAR(30) NULL DEFAULT NULL,
  `id_depart` INT(11) NULL DEFAULT NULL,
  `current_mail_teach` VARCHAR(60) NOT NULL,
  `current_phone_teach` VARCHAR(11) NULL DEFAULT NULL,
  `photo_teach` VARCHAR(50) NULL DEFAULT 'default.png',
  `internal_phone` VARCHAR(4) NULL DEFAULT NULL,
  `id_user_teach` INT(11) NOT NULL,
  PRIMARY KEY (`id_teach`),
  UNIQUE INDEX `current_mail_teach_UNIQUE` (`current_mail_teach` ASC) VISIBLE,
  UNIQUE INDEX `current_mail_teach` (`current_mail_teach` ASC, `current_phone_teach` ASC) VISIBLE,
  UNIQUE INDEX `current_phone_teach_UNIQUE` (`current_phone_teach` ASC) VISIBLE,
  INDEX `id_depart` (`id_depart` ASC) VISIBLE,
  CONSTRAINT `teach_ibfk_1`
    FOREIGN KEY (`id_depart`)
    REFERENCES `KOD`.`depart` (`id_depart`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`teach_degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`teach_degree` (
  `td_id_teach` INT(11) NOT NULL,
  `td_id_degree` INT(11) NOT NULL,
  PRIMARY KEY (`td_id_teach`, `td_id_degree`),
  INDEX `fk_td_id_degree_idx` (`td_id_degree` ASC) VISIBLE,
  CONSTRAINT `fk_td_id_degree`
    FOREIGN KEY (`td_id_degree`)
    REFERENCES `KOD`.`degree` (`id_degree`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_td_id_teach`
    FOREIGN KEY (`td_id_teach`)
    REFERENCES `KOD`.`teach` (`id_teach`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`teach_discipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`teach_discipline` (
  `th_dis_class_id` INT(11) NOT NULL,
  `th_teach_id` INT(11) NOT NULL,
  PRIMARY KEY (`th_dis_class_id`, `th_teach_id`),
  INDEX `fk_th_teach_id_idx` (`th_teach_id` ASC) VISIBLE,
  CONSTRAINT `fk_th_dis_class_id`
    FOREIGN KEY (`th_dis_class_id`)
    REFERENCES `KOD`.`discipline_class_type` (`id_dis_class`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_th_teach_id`
    FOREIGN KEY (`th_teach_id`)
    REFERENCES `KOD`.`teach` (`id_teach`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `KOD`.`teach_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KOD`.`teach_post` (
  `tp_id_teach` INT(11) NOT NULL,
  `tp_id_post` INT(11) NOT NULL,
  PRIMARY KEY (`tp_id_teach`, `tp_id_post`),
  INDEX `fk_id_post_idx` (`tp_id_post` ASC) VISIBLE,
  CONSTRAINT `fk_tp_id_post`
    FOREIGN KEY (`tp_id_post`)
    REFERENCES `KOD`.`post` (`id_post`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tp_id_teach`
    FOREIGN KEY (`tp_id_teach`)
    REFERENCES `KOD`.`teach` (`id_teach`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
